"""Abstract repository protocols for the Identity bounded context."""
from typing import Protocol
from uuid import UUID

from .entities import User, UserSession


class IUserRepository(Protocol):
    async def get_by_id(self, user_id: UUID) -> User | None: ...
    async def get_by_email(self, email: str) -> User | None: ...
    async def get_by_username(self, username: str) -> User | None: ...
    async def save(self, user: User) -> User: ...
    async def delete(self, user_id: UUID) -> None: ...


class IUserSessionRepository(Protocol):
    async def get_by_jti_hash(self, jti_hash: str) -> UserSession | None: ...
    async def get_active_by_user_id(self, user_id: UUID) -> list[UserSession]: ...
    async def save(self, session: UserSession) -> UserSession: ...
    async def revoke(self, session_id: UUID) -> None: ...
    async def revoke_all_for_user(self, user_id: UUID) -> None: ...
