services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      ENVIRONMENT: development
      STORAGE_PATH: /app/storage
    network_mode: host
    volumes:
      - ./backend/src:/app/src:z
      - backend_storage:/app/storage

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    network_mode: host
    volumes:
      - ./frontend/src:/app/src:z

volumes:
  backend_storage:
