"""Abstract repository protocols for the Finance bounded context."""
from datetime import date
from typing import Protocol
from uuid import UUID

from .entities import (
    Account,
    Transaction,
    TransactionCategory,
    TransactionComment,
    TransactionGroup,
)


class IAccountRepository(Protocol):
    async def get_by_id(self, account_id: UUID, user_id: UUID) -> Account | None: ...
    async def list_by_user(self, user_id: UUID) -> list[Account]: ...
    async def save(self, account: Account) -> Account: ...
    async def delete(self, account_id: UUID, user_id: UUID) -> None: ...


class ITransactionCategoryRepository(Protocol):
    async def get_by_id(self, category_id: UUID, user_id: UUID) -> TransactionCategory | None: ...
    async def list_tree_by_user(self, user_id: UUID) -> list[TransactionCategory]: ...
    async def save(self, category: TransactionCategory) -> TransactionCategory: ...
    async def delete(self, category_id: UUID, user_id: UUID) -> None: ...


class ITransactionRepository(Protocol):
    async def get_by_id(self, transaction_id: UUID, user_id: UUID) -> Transaction | None: ...
    async def list_by_user(
        self,
        user_id: UUID,
        *,
        date_from: date | None = None,
        date_to: date | None = None,
        account_id: UUID | None = None,
        category_id: UUID | None = None,
        limit: int = 50,
        offset: int = 0,
    ) -> list[Transaction]: ...
    async def count_by_user(
        self,
        user_id: UUID,
        *,
        date_from: date | None = None,
        date_to: date | None = None,
        account_id: UUID | None = None,
        category_id: UUID | None = None,
    ) -> int: ...
    async def save(self, transaction: Transaction) -> Transaction: ...
    async def bulk_save(self, transactions: list[Transaction]) -> list[Transaction]: ...
    async def delete(self, transaction_id: UUID, user_id: UUID) -> None: ...


class ITransactionCommentRepository(Protocol):
    async def list_by_transaction(self, transaction_id: UUID, user_id: UUID) -> list[TransactionComment]: ...
    async def save(self, comment: TransactionComment) -> TransactionComment: ...
    async def delete(self, comment_id: UUID, user_id: UUID) -> None: ...


class ITransactionGroupRepository(Protocol):
    async def get_by_id(self, group_id: UUID, user_id: UUID) -> TransactionGroup | None: ...
    async def list_by_user(self, user_id: UUID) -> list[TransactionGroup]: ...
    async def save(self, group: TransactionGroup) -> TransactionGroup: ...
    async def add_member(self, group_id: UUID, transaction_id: UUID) -> None: ...
    async def remove_member(self, group_id: UUID, transaction_id: UUID) -> None: ...
    async def list_group_transactions(self, group_id: UUID, user_id: UUID) -> list[Transaction]: ...
    async def delete(self, group_id: UUID, user_id: UUID) -> None: ...
