"""Abstract repository protocols for the Document bounded context."""
from typing import Protocol
from uuid import UUID

from .entities import OcrJob, StagingTransaction


class IOcrJobRepository(Protocol):
    async def get_by_id(self, job_id: UUID, user_id: UUID) -> OcrJob | None: ...
    async def get_by_file_hash(self, file_hash: str, user_id: UUID) -> OcrJob | None: ...
    async def list_by_user(self, user_id: UUID, limit: int = 20, offset: int = 0) -> list[OcrJob]: ...
    async def save(self, job: OcrJob) -> OcrJob: ...


class IStagingTransactionRepository(Protocol):
    async def list_by_job(self, job_id: UUID, user_id: UUID) -> list[StagingTransaction]: ...
    async def get_by_id(self, staging_id: UUID, user_id: UUID) -> StagingTransaction | None: ...
    async def save(self, staging: StagingTransaction) -> StagingTransaction: ...
    async def bulk_save(self, stagings: list[StagingTransaction]) -> list[StagingTransaction]: ...
    async def delete(self, staging_id: UUID, user_id: UUID) -> None: ...
    async def delete_by_job(self, job_id: UUID) -> None: ...
